# Generated by Django 4.1.7 on 2023-04-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhsapp', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
