# Generated by Django 4.1.7 on 2023-05-06 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fhsapp', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fhsapp.registration'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('user', 'item_name')},
        ),
    ]
