# Generated by Django 4.1.7 on 2023-05-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhsapp', '0005_order_user_alter_order_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordertime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
