# Generated by Django 4.1.7 on 2023-05-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhsapp', '0006_order_ordertime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
